kind = "mobile"
previewPath = "/"
title = "Serategna"
version = "1.0.0"
id = "artifacts/serategna"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 25617

[services.development]
run = "pnpm --filter @workspace/serategna run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/serategna", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/serategna", "run", "serve" ]

[services.env]
PORT = "25617"
BASE_PATH = "/"
